version: '3'
services:
  reverse-proxy:
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
  
  service1:
    image: containous/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.service1.rule=Host(`first.localhost`)"

  service2:
    image: containous/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.service2.rule=Host(`second.localhost`)"
