version: '3'
services:
  reverse-proxy:
    image: traefik:latest
    command:
      --api.insecure=true
      --providers.docker
      --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  service1:
    image: containous/whoami
    labels: 
      - "traefik.http.routers.service1.rule=Host(`first.localhost`)"

  service2:
    image: containous/whoami
    labels: 
      - "traefik.http.routers.service2.rule=Host(`second.localhost`)"
